### ISSUE TITLE
Party is Lost Upon Map Change

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MSCScripts#224] opened 2022-12-28 17:37 UTC
joinparty command works properly, and the chat functions seem to work (haven't yet tested with another player), yet upon map transition, the party is disbanded and needs to be re-formed.

**Comment by SaintWish** [comment] 2022-12-28 19:49
Duplicate of https://github.com/MSRevive/MasterSwordRebirth/issues/96

**Closed as not planned** 2022-12-30 00:26 UTC
