### ISSUE TITLE
Lightning shamans in Cleicert dont shoot their lightning orbs

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MSCScripts#69] opened 2022-07-10 00:34 UTC
Probably an issue with the projectile's parameters, check to see if the starting point is correct

**Comment by greatguys1** [comment] 2022-07-10 00:59
This issue seems to be bigger than this, check the_keep archers to verify, then edit this issue.

**Comment by Charles445** [comment] 2022-09-03 03:48
Seems to be a really weird bug with scripting and game_spawn

https://github.com/MSRevive/MSCScripts/blob/MSCScript-alpha/scripts/items/proj_lightning_ball.script#L42
`callevent 10.0 remove_me`
Seems to be because it's part of a series of callevent that starts with game_spawn (???)
This callevent actually tries to run twice, once at 0 seconds, and another when it's supposed to

The weird part is this doesn't happen with callexternal
`callexternal ent_me 10.0 remove_me`
works fine

So it's something to do with game_spawn... I can't figure it out though
Like something is looping through all the queued up things and running them all at once, and leaving them in the queue, for some inexplicable reason

**Comment by Charles445** [comment] 2022-09-03 07:10
The lightning balls, even if they weren't being deleted, still don't work due to some sort of bug with getents
`getents any SCAN_SIZE`
Now that the lightning balls pass through players, they rely on the entity scan
It's supposed to scan at the origin pos of the lightning ball, but it doesn't seem to work

`getents any SCAN_SIZE $relpos(0,0,0)`
This works, however, so something is broken

`. getents any 1000.0`
In the console behaves very strangely, seems to miss most entities

$relpos uses Center( ) and pev->origin, so maybe getents needs to use Center( ) where it can

**Comment by Charles445** [comment] 2022-09-03 08:39
OKAY, I believe I've figured it out.

There is a call to game_spawn in the GlobalItem version of the items
https://github.com/MSRevive/MasterSwordRebirth/blob/dev/game/shared/weapons/genericitem.cpp#L81-L99

The problem is, the GlobalItem here starts the timer on its own, and then gives that same timer to any new items that get created (somehow).
So, after the duration of the timer (in this case 10 seconds) any new lightning balls will be instantly removed.

The best solution is probably to stop GlobalItem from starting timers (it can't complete them I don't think)

If that isn't possible, this is a workaround using the game_spawn param that GlobalItems are given (make sure to remove the old callevent from arrow_spawn)
```
{ game_spawn
	if ( PARAM1 isnot 1 ) callevent 10.0 remove_me
}
```

If the workaround is used, make sure to look for any other scripts using timers in game_spawn

**Comment by SaintWish** [comment] 2022-09-03 23:53
Fix'd with this commit https://github.com/MSRevive/MasterSwordRebirth/commit/7ea4a36b5e061b2954cadce4643c453d363e5d82 but it might break other stuff so needs further testing!

**Comment by Charles445** [comment] 2022-09-04 01:55
Now that getents is fixed, these used scripts are affected and need testing

```
furion\dragoons\dragoon_boss_base.script	(sweep kick with three players nearby)
items\proj_lightning_ball.script		(sorc shamans)
monsters\bandit_boss.script			(sweep kick with three players nearby, all bosses except orion)
monsters\summon\poison_cloud.script		(player made poison cloud from a scroll or tome)
monsters\summon\uber_blizzard.script		(bear god, uber reaver, ice alpha wolf)
outpost\super.script				(some sort of map cheese protection?)
```

**Comment by greatguys1** [comment] 2022-09-04 22:04
> The weird part is this doesn't happen with callexternal `callexternal ent_me 10.0 remove_me` works fine
`callexternal ent_me 10.0 remove_me`
callexternal cant be used with a timer. In this example, I think you're calling event "10.0" with the parameter of "remove_me", which is probably why it doesn't get removed anymore. But the other example: 
>`{ game_spawn
	if ( PARAM1 isnot '1' ) callevent 10.0 remove_me
}`
 is the fix you're looking for. I add single quote around the 1 though, since strings are a little bit weird.

**Comment by Charles445** [comment] 2022-09-05 01:09
callexternal surprisingly can be used with a timer, there's some code for it. The example I gave worked well, but I worded it poorly.
It's 'callexternal all' that won't work.

As for the use of '1', I'm not sure if the scripting language makes a distinction about that sort of thing, I think it just assumes everything is a string, and parses it when it needs to (for example, armor resistance being '55%', yet works as 55 when used in arithmetic)


Also getents should be fixed now!
https://github.com/MSRevive/MasterSwordRebirth/commit/698d2d9d10f5f1d28a47ef6ea95c136bf0328ca3
So in theory this bug should be completely gone, needs testing though

**Comment by Charles445** [comment] 2022-09-05 14:15
It works, but it has a couple of issues

1. Instead of doing the flat impact damage + one shock, it shocks the player every tenth of a second as it passes through them, either doing barely any damage or melting them instantly, very inconsistent
2. When the projectile collides with a wall, the random sound does not play

I personally like an older implementation better, where PROJ_IGNORENPC is 0, and hit_target is never called

**Comment by greatguys1** [comment] 2022-10-04 18:47
Sorry for taking ages to reply


> callexternal surprisingly can be used with a timer, there's some code for it. The example I gave worked well, but I worded it poorly. It's 'callexternal all' that won't work.

Oh wow that surprises me, thanks for clarifying that for me


> It works, but it has a couple of issues
> 
> 1. Instead of doing the flat impact damage + one shock, it shocks the player every tenth of a second as it passes through them, either doing barely any damage or melting them instantly, very inconsistent
> 2. When the projectile collides with a wall, the random sound does not play
> 
> I personally like an older implementation better, where PROJ_IGNORENPC is 0, and hit_target is never called (commenting out callevent scan_damage)

I'll test out both implementations, thanks for testing and fixing

**Closed** 2022-11-09 04:58 UTC
Labels: bug 🐛, high priority
