### ISSUE TITLE
Edana/Edrin Captain of the Guard

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/MSCScripts#95] opened 2022-10-10 04:09 UTC
He doesn't yell at you properly when you trample the flowers in Edana's town square. He kind of gets stuck in the same spot right in front of the garden every time and doesn't say anything. You can kick him around to reset the movement but he will just run back to the same stuck spot.

**Comment by SaintWish** [comment] 2022-10-10 04:38
Duplicate of https://github.com/MSRevive/MSCScripts/issues/42

**Closed as not planned by SaintWish** 2022-10-10 04:38 UTC
