### ISSUE TITLE
Some races get displayed as Hostile when they should not.

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/MSCScripts#90] opened 2022-10-08 07:41 UTC
![image](https://user-images.githubusercontent.com/85242183/194696126-41323b38-119a-4d17-a632-cffab5c2f042.png)

Edana priest as example. In this case he cannot be damaged or attacked, but shows up as Hostile.

**Comment by SaintWish** [comment] 2022-10-08 21:18
Seems to be caused by their race, because your "relationship" to via NPC is determined by what race they are. As pointed out by @Dridje ``hguard`` is set to hostile relationship.

**Comment by SaintWish** [comment] 2022-10-15 21:27
With the latest update helena guards are now marked as "Wary" and all friendly NPCs in edana are marked as "Friendly" now.

**Closed as completed by SaintWish** 2022-10-15 21:27 UTC
Labels: bug 🐛, low priority
