### ISSUE TITLE
Picking up trollcano will crash the server

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MSCScripts#20] opened 2022-03-28 20:18 UTC
Tried to pick up this spell -> crashed

**Comment by BerntA** [comment] 2022-03-28 20:22
Only crashes for ppl not eligible to pick it up

**Comment by greatguys1** [comment] 2022-07-04 10:22
I can't reproduce this issue. Does this only happen on linux servers?

**Comment by greatguys1** [comment] 2022-10-17 23:23
I havent seen this happen after many different testing environments. Will close this as fixed.

**Closed by greatguys1** 2022-10-17 23:23 UTC
Labels: bug 🐛, help wanted, linux
